export const TEAM_CRESTS: Record<string, string> = {
  "Uruguay": "https://crests.football-data.org/758.svg",
  "Germany": "https://crests.football-data.org/759.svg",
  "Spain": "https://crests.football-data.org/760.svg",
  "Paraguay": "https://crests.football-data.org/761.svg",
  "Argentina": "https://crests.football-data.org/762.png",
  "Ghana": "https://crests.football-data.org/ghana.svg",
  "Brazil": "https://crests.football-data.org/764.svg",
  "Portugal": "https://crests.football-data.org/765.svg",
  "Japan": "https://crests.football-data.org/766.svg",
  "Mexico": "https://crests.football-data.org/769.svg",
  "England": "https://crests.football-data.org/770.svg",
  "United States": "https://crests.football-data.org/usa.svg",
  "South Korea": "https://crests.football-data.org/772.png",
  "France": "https://crests.football-data.org/773.svg",
  "South Africa": "https://crests.football-data.org/9396.svg",
  "Algeria": "https://crests.football-data.org/algeria.svg",
  "Australia": "https://crests.football-data.org/779.svg",
  "New Zealand": "https://crests.football-data.org/783.svg",
  "Switzerland": "https://crests.football-data.org/788.svg",
  "Ecuador": "https://crests.football-data.org/791.svg",
  "Sweden": "https://crests.football-data.org/792.svg",
  "Czechia": "https://crests.football-data.org/798.svg",
  "Croatia": "https://crests.football-data.org/799.svg",
  "Saudi Arabia": "https://crests.football-data.org/saudi_arabia.svg",
  "Tunisia": "https://crests.football-data.org/tunisia.svg",
  "Turkiye": "https://crests.football-data.org/803.svg",
  "Senegal": "https://crests.football-data.org/senegal.svg",
  "Belgium": "https://crests.football-data.org/805.svg",
  "Morocco": "https://crests.football-data.org/morocco.svg",
  "Austria": "https://crests.football-data.org/816.svg",
  "Colombia": "https://crests.football-data.org/818.svg",
  "Egypt": "https://crests.football-data.org/825.svg",
  "Canada": "https://crests.football-data.org/canada.svg",
  "Haiti": "https://crests.football-data.org/haiti.svg",
  "Iran": "https://crests.football-data.org/iran.svg",
  "Bosnia-Herzegovina": "https://crests.football-data.org/bosnia.svg",
  "Panama": "https://crests.football-data.org/panama.svg",
  "Cape Verde": "https://crests.football-data.org/cape_verde.svg",
  "Congo DR": "https://crests.football-data.org/congo_dr.svg",
  "Cote d'Ivoire": "https://crests.football-data.org/787.svg",
  "Qatar": "https://crests.football-data.org/8030.svg",
  "Jordan": "https://crests.football-data.org/8049.png",
  "Iraq": "https://crests.football-data.org/iraq.svg",
  "Uzbekistan": "https://crests.football-data.org/8070.png",
  "Netherlands": "https://crests.football-data.org/8601.svg",
  "Norway": "https://crests.football-data.org/813.svg",
  "Scotland": "https://crests.football-data.org/814.svg",
  "Curacao": "https://crests.football-data.org/curacao.svg"
};
