export const TEAM_NAMES_ES: Record<string, string> = {
  Algeria: "Argelia",
  Argentina: "Argentina",
  Australia: "Australia",
  Austria: "Austria",
  Belgium: "Bélgica",
  Bolivia: "Bolivia",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  Brazil: "Brasil",
  Cameroon: "Camerún",
  Canada: "Canadá",
  "Cape Verde": "Cabo Verde",
  "Cape Verde Islands": "Cabo Verde",
  Chile: "Chile",
  China: "China",
  Colombia: "Colombia",
  "Congo DR": "RD Congo",
  "Costa Rica": "Costa Rica",
  "Cote d'Ivoire": "Costa de Marfil",
  "Côte d'Ivoire": "Costa de Marfil",
  Croatia: "Croacia",
  Cuba: "Cuba",
  Curacao: "Curazao",
  Curaçao: "Curazao",
  Czechia: "República Checa",
  Denmark: "Dinamarca",
  Ecuador: "Ecuador",
  Egypt: "Egipto",
  "El Salvador": "El Salvador",
  England: "Inglaterra",
  "Equatorial Guinea": "Guinea Ecuatorial",
  France: "Francia",
  Gambia: "Gambia",
  Germany: "Alemania",
  Ghana: "Ghana",
  Greece: "Grecia",
  Guatemala: "Guatemala",
  Guinea: "Guinea",
  Haiti: "Haití",
  Honduras: "Honduras",
  Hungary: "Hungría",
  Iceland: "Islandia",
  India: "India",
  Indonesia: "Indonesia",
  Iran: "Irán",
  Iraq: "Irak",
  Italy: "Italia",
  "Ivory Coast": "Costa de Marfil",
  Jamaica: "Jamaica",
  Japan: "Japón",
  Jordan: "Jordania",
  Kenya: "Kenia",
  Mali: "Malí",
  Mexico: "México",
  Morocco: "Marruecos",
  Netherlands: "Países Bajos",
  "New Zealand": "Nueva Zelanda",
  Nigeria: "Nigeria",
  Norway: "Noruega",
  Oman: "Omán",
  Panama: "Panamá",
  Paraguay: "Paraguay",
  Peru: "Perú",
  Poland: "Polonia",
  Portugal: "Portugal",
  Qatar: "Catar",
  Romania: "Rumania",
  "Saudi Arabia": "Arabia Saudita",
  Scotland: "Escocia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Slovakia: "Eslovaquia",
  Slovenia: "Eslovenia",
  "South Africa": "Sudáfrica",
  "South Korea": "Corea del Sur",
  Spain: "España",
  Sweden: "Suecia",
  Switzerland: "Suiza",
  Tanzania: "Tanzania",
  Thailand: "Tailandia",
  Trinidad: "Trinidad y Tobago",
  Tunisia: "Túnez",
  Turkiye: "Turquía",
  Uganda: "Uganda",
  Ukraine: "Ucrania",
  "United Arab Emirates": "Emiratos Árabes",
  "United States": "Estados Unidos",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistán",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  Wales: "Gales",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabue",
};

export const TEAM_FLAGS: Record<string, string> = {
  // ── Americas ──
  Argentina: "🇦🇷",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  Colombia: "🇨🇴",
  Ecuador: "🇪🇨",
  Mexico: "🇲🇽",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  "United States": "🇺🇸",
  Uruguay: "🇺🇾",
  Peru: "🇵🇪",
  Chile: "🇨🇱",
  Bolivia: "🇧🇴",
  Venezuela: "🇻🇪",
  Honduras: "🇭🇳",
  "El Salvador": "🇸🇻",
  Jamaica: "🇯🇲",
  Haiti: "🇭🇹",
  Cuba: "🇨🇺",
  Curacao: "🇨🇼",
  Curaçao: "🇨🇼",
  "Costa Rica": "🇨🇷",
  Guatemala: "🇬🇹",
  Trinidad: "🇹🇹",
  // ── Europe ──
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Croatia: "🇭🇷",
  Czechia: "🇨🇿",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Italy: "🇮🇹",
  Netherlands: "🇳🇱",
  Norway: "🇳🇴",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Serbia: "🇷🇸",
  Spain: "🇪🇸",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Turkiye: "🇹🇷",
  Ukraine: "🇺🇦",
  Denmark: "🇩🇰",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  Greece: "🇬🇷",
  Iceland: "🇮🇸",
  Albania: "🇦🇱",
  "Bosnia-Herzegovina": "🇧🇦",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  // ── Africa ──
  Algeria: "🇩🇿",
  "Cape Verde": "🇨🇻",
  "Cape Verde Islands": "🇨🇻",
  "Congo DR": "🇨🇩",
  "Cote d'Ivoire": "🇨🇮",
  Egypt: "🇪🇬",
  Ghana: "🇬🇭",
  Morocco: "🇲🇦",
  Nigeria: "🇳🇬",
  Senegal: "🇸🇳",
  "South Africa": "🇿🇦",
  Tunisia: "🇹🇳",
  Cameroon: "🇨🇲",
  Mali: "🇲🇱",
  Kenya: "🇰🇪",
  Tanzania: "🇹🇿",
  Uganda: "🇺🇬",
  Zambia: "🇿🇲",
  Zimbabwe: "🇿🇼",
  Guinea: "🇬🇳",
  "Equatorial Guinea": "🇬🇶",
  Gambia: "🇬🇲",
  // ── Asia & Oceania ──
  Australia: "🇦🇺",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Japan: "🇯🇵",
  Jordan: "🇯🇴",
  "Saudi Arabia": "🇸🇦",
  "South Korea": "🇰🇷",
  Qatar: "🇶🇦",
  Uzbekistan: "🇺🇿",
  "New Zealand": "🇳🇿",
  Indonesia: "🇮🇩",
  "United Arab Emirates": "🇦🇪",
  Bahrain: "🇧🇭",
  Oman: "🇴🇲",
  China: "🇨🇳",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  India: "🇮🇳",
  Taiwan: "🇹🇼",
};
